/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/csv",
  "go": "github.com/tabnas/csv/go",
  "description": "CSV (RFC 4180) parsing for the tabnas engine.",
  "base": "@tabnas/jsonic",
  "engine": "@tabnas/parser",
  "grammar": "csv-grammar.jsonic",
  "extensions": [
    ".csv"
  ],
  "mediaTypes": [
    "text/csv"
  ],
  "languageId": "csv",
  "pluginKind": "grammar",
  "grammarKind": "closure",
  "lexStream": "clean",
  "syncGroups": [
    "end",
    "comma"
  ],
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnascsv",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [
    "csv_extra_field",
    "csv_missing_field"
  ],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/csv",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "records",
    "render": "csv",
    "loss": [
      "A null and a missing cell are both written as the empty field, so the two cannot be told apart, or from an empty string, when read back.",
      "A nested array or object in a cell is written as its compact JSON text.",
      "Every field is written quoted.",
      "Records end in CRLF.",
      "Every value is written as text, so a number or a boolean reads back as a string."
    ]
  }
}
`,
  render: Object.freeze({ entry: "csv" })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
